invenio_curations/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024-2026 Graz University of Technology.
#
# Invenio-Curations is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

"""Invenio module for curation support."""

from .ext import InvenioCurations
from .proxies import current_curations, current_curations_service

__version__ = "0.7.0"

__all__ = (
    "InvenioCurations",
    "__version__",
    "current_curations",
    "current_curations_service",
)

invenio_curations/notifications/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2025 Graz University of Technology.
#
# Invenio-Curations is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

"""Notification module."""

invenio_curations/requests/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 Graz University of Technology.
#
# Invenio-Curations is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

"""Resources module."""

from .curation import CurationRequest

__all__ = ("CurationRequest",)

invenio_curations/resources/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 Graz University of Technology.
#
# Invenio-Curations is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

"""Resources module."""

from .config import CurationsResourceConfig
from .resource import CurationsResource

__all__ = (
    "CurationsResource",
    "CurationsResourceConfig",
)

invenio_curations/services/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024-2025 Graz University of Technology.
#
# Invenio-Curations is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

"""Resources module."""

from .config import CurationsServiceConfig
from .service import CurationRequestService

__all__ = (
    "CurationRequestService",
    "CurationsServiceConfig",
)

invenio_curations/views/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024-2025 Graz University of Technology.
#
# Invenio-Curations is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

"""Curations views module."""

from flask import Blueprint

from .api import create_curations_bp
from .ui import create_ui_blueprint

blueprint = Blueprint("invenio-curations-ext", __name__)

__all__ = (
    "blueprint",
    "create_curations_bp",
    "create_ui_blueprint",
)

invenio_curations/views/api.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024-2025 Graz University of Technology.
#
# Invenio-Curations is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""View functions for curations."""

from typing import cast

from flask import Blueprint, Flask


def create_curations_bp(app: Flask) -> Blueprint:
    """Create curations blueprint."""
    ext = app.extensions["invenio-curations"]
    return cast(Blueprint, ext.curations_resource.as_blueprint())

invenio_curations/views/ui.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024-2025 Graz University of Technology.
#
# Invenio-Curations is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Curations ui views module."""

from typing import cast

from flask import Blueprint, Flask, abort, g, render_template
from flask_login import current_user
from flask_principal import Identity
from invenio_records_resources.services.records.service import RecordService
from invenio_users_resources.proxies import current_user_resources

from ..proxies import current_curations_service, unproxy
from ..searchapp import search_app_context
from ..services import CurationRequestService


def user_has_curations_management_role(identity: Identity) -> bool:
    """Check if provided identity provides the curation role."""
    _curations_service: CurationRequestService = unproxy(current_curations_service)
    role = _curations_service.moderation_role
    if not role:
        return False
    return cast(bool, identity.user.has_role(role))


def curation_requests_overview() -> str:
    """Display user dashboard page."""
    if not user_has_curations_management_role(g.identity):
        abort(403)

    user_service_unproxied: RecordService = unproxy(
        current_user_resources.users_service,
    )
    url = user_service_unproxied.links_item_tpl.expand(g.identity, current_user)[
        "avatar"
    ]

    return render_template(
        "invenio_curations/overview.html",
        searchbar_config=dict(searchUrl="/"),
        user_avatar=url,
    )


def create_ui_blueprint(app: Flask) -> Blueprint:  # noqa: ARG001
    """Register blueprint routes on app."""
    blueprint = Blueprint(
        "invenio_curations",
        __name__,
        template_folder="../templates",
        static_folder="../static",
    )

    # Add URL rules
    blueprint.add_url_rule("/curations/overview", view_func=curation_requests_overview)

    # Add context processor for search
    blueprint.app_context_processor(search_app_context)
    return blueprint

invenio_curations/templates/semantic-ui/invenio_curations/overview.html
{#
Copyright (C) 2020 CERN.
Copyright (C) 2020 Northwestern University.
Copyright (C) 2024 Graz University of Technology.

Invenio-Curations is free software; you can redistribute it and/or modify it
under the terms of the MIT License; see LICENSE file for more details.
#}
{%- set title = _("Requests") %}
{%- extends "invenio_app_rdm/users/base.html" %}

{% set active_dashboard_menu_item = 'curation-overview' %}

{%- block javascript %}
{{ super() }}
{{ webpack['invenio-app-rdm-user-requests.js'] }}
{%- endblock javascript %}

{%- block user_dashboard_body %}

<div id="invenio-search-config"
  data-invenio-search-config='{{ search_app_curations_requests_config(app_id="InvenioAppRdm.DashboardRequests") | tojson }}'>
</div>

{%- endblock user_dashboard_body %}

invenio_curations/templates/semantic-ui/invenio_notifications/curation-request.accept.jinja
{% set curation_request = notification.context.request %}
{% set group = curation_request.receiver %}
{% set creator = curation_request.created_by %}
{% set record = curation_request.topic %}
{% set request_id = curation_request.id %}
{% set executing_user = notification.context.executing_user %}
{% set message = notification.context.message | safe if notification.context.message else '' %}
{% set record_title = record.metadata.title %}
{% set curator_name = executing_user.profile.full_name %}
{% if not curator_name  %} 
    {% set curator_name = executing_user.email %}
{% else %} 
    {% set curator_name = curator_name +  " - " + executing_user.email %} 
{% endif %}

{# TODO: use request.links.self_html when issue issue is resolved: https://github.com/inveniosoftware/invenio-rdm-records/issues/1327 #}
{% set request_link = "{ui}/me/requests/{id}".format(
    ui=config.SITE_UI_URL, id=request_id
    )
%}
{% set account_settings_link = "{ui}/account/settings/notifications".format(
    ui=config.SITE_UI_URL
    )
%}

{%- block subject -%}
       {{ _("✅ Curation request accepted for '{record_title}'").format(record_title=record_title) }}
{%- endblock subject -%}

{%- block html_body -%}
    <table style="font-family:'Lato',Helvetica,Arial,sans-serif;border-spacing:15px">
        <tr>
            <td>{{ _("The metadata curator '{curator_name}' accepted the record '{record_title}'").format(curator_name=curator_name, record_title=record_title) }}
            {% if message %} 
            {{ _(" with the following message:")}}
            {% endif %}
            </td>
        </tr>
        <tr>
            {% if message %} 
            <td><em>{{message}}</em></td>
            {% endif %}
        </tr>
        <tr>
            <td><a href="{{ request_link }}" class="button">{{ _("Check out the curation request")}}</a></td>
        </tr>
        <tr>
            <td><strong>_</strong></td>
        </tr>
        <tr>
            <td style="font-size:smaller">{{ _("This is an auto-generated message. To manage notifications, visit your")}} <a href="{{account_settings_link}}">{{ _("account settings")}}</a>.</td>
        </tr>
    </table>
{%- endblock html_body %}

{%- block plain_body -%}
{{ _("The metadata curator {curator_name} accepted the record '{record_title}'").format(curator_name=curator_name, record_title=record_title) }}

{% if message %} 
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Check out the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock plain_body %}

{# Markdown for Slack/Mattermost/chat #}
{%- block md_body -%}
{{ _("The metadata curator *{curator_name}* accepted the record *{record_title}*").format(curator_name=curator_name, record_title=record_title) }}

{% if message %} 
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Check out the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock md_body %}

invenio_curations/templates/semantic-ui/invenio_notifications/curation-request.critique.jinja
{% set curation_request = notification.context.request %}
{% set group = curation_request.receiver %}
{% set creator = curation_request.created_by %}
{% set record = curation_request.topic %}
{% set request_id = curation_request.id %}
{% set executing_user = notification.context.executing_user %}
{% set message = notification.context.message | safe if notification.context.message else '' %}
{% set record_title = record.metadata.title %}
{% set curator_name = executing_user.profile.full_name %}
{% if not curator_name  %} 
    {% set curator_name = executing_user.email %}
{% else %} 
    {% set curator_name = curator_name +  " - " + executing_user.email %} 
{% endif %}

{# TODO: use request.links.self_html when issue issue is resolved: https://github.com/inveniosoftware/invenio-rdm-records/issues/1327 #}
{% set request_link = "{ui}/me/requests/{id}".format(
    ui=config.SITE_UI_URL, id=request_id
    )
%}
{% set account_settings_link = "{ui}/account/settings/notifications".format(
    ui=config.SITE_UI_URL
    )
%}

{%- block subject -%}
       {{ _("📝 Curation request critiqued for '{record_title}'").format(record_title=record_title) }}
{%- endblock subject -%}

{%- block html_body -%}
    <table style="font-family:'Lato',Helvetica,Arial,sans-serif;border-spacing:15px">
        <tr>
            <td>{{ _("The metadata curator '{curator_name}' critiqued the record '{record_title}'").format(curator_name=curator_name, record_title=record_title) }}
            {% if message %} 
            {{ _(" with the following message:")}}
            {% endif %}
            </td>
        </tr>
        <tr>
            {% if message %} 
            <td><em>{{message}}</em></td>
            {% endif %}
        </tr>
        <tr>
            <td><a href="{{ request_link }}" class="button">{{ _("Check out the curation request")}}</a></td>
        </tr>
        <tr>
            <td><strong>_</strong></td>
        </tr>
        <tr>
            <td style="font-size:smaller">{{ _("This is an auto-generated message. To manage notifications, visit your")}} <a href="{{account_settings_link}}">{{ _("account settings")}}</a>.</td>
        </tr>
    </table>
{%- endblock html_body %}

{%- block plain_body -%}
{{ _("The metadata curator {curator_name} critiqued the record '{record_title}'").format(curator_name=curator_name, record_title=record_title) }}

{% if message %} 
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Check out the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock plain_body %}

{# Markdown for Slack/Mattermost/chat #}
{%- block md_body -%}
{{ _("The metadata curator *{curator_name}* critiqued the record *{record_title}*").format(curator_name=curator_name, record_title=record_title) }}

{% if message %} 
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Check out the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock md_body %}

invenio_curations/templates/semantic-ui/invenio_notifications/curation-request.resubmit.jinja
{% set curation_request = notification.context.request %}
{% set group = curation_request.receiver %}
{% set creator = curation_request.created_by %}
{% set record = curation_request.topic %}
{% set request_id = curation_request.id %}
{% set creator_name = creator.profile.full_name %}
{% if not creator_name  %} 
    {% set creator_name = creator.email %}
{% else %} 
    {% set creator_name = creator_name +  " - " + creator.email %} 
{% endif %}
{% set record_title = record.metadata.title %}
{% set message = notification.context.message | safe if notification.context.message else '' %}

{# TODO: use request.links.self_html when issue issue is resolved: https://github.com/inveniosoftware/invenio-rdm-records/issues/1327 #}
{% set request_link = "{ui}/me/requests/{id}".format(
    ui=config.SITE_UI_URL, id=request_id
    )
%}
{% set account_settings_link = "{ui}/account/settings/notifications".format(
    ui=config.SITE_UI_URL
    )
%}

{%- block subject -%}
       {{ _("📥 Curation request resubmitted") }}
{%- endblock subject -%}

{%- block html_body -%}
    <table style="font-family:'Lato',Helvetica,Arial,sans-serif;border-spacing:15px">
        <tr>
            <td>{{ _("The record '{record_title}' was resubmitted for curation by '{creator_name}'").format(record_title=record_title, creator_name=creator_name) }}
            {% if message %} 
            {{ _(" with the following message:")}}
            {% endif %}
            </td>
        </tr>
        <tr>
            {% if message %} 
            <td><em>{{message}}</em></td>
            {% endif %}
        </tr>
        <tr>
            <td><a href="{{request_link}}" class="button">{{ _("Review the curation request")}}</a></td>
        </tr>
        <tr>
            <td><strong>_</strong></td>
        </tr>
        <tr>
            <td style="font-size:smaller">{{ _("This is an auto-generated message. To manage notifications, visit your")}} <a href="{{account_settings_link}}">{{ _("account settings")}}</a>.</td>
        </tr>
    </table>
{%- endblock html_body %}

{%- block plain_body -%}
    {{ _("The record '{record_title}' was resubmitted for curation by '{creator_name}'.").format(record_title=record_title, creator_name=creator_name) }}

{% if message %} 
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Review the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock plain_body %}

{# Markdown for Slack/Mattermost/chat #}
{%- block md_body -%}
{{ _("The record *'{record_title}'* was resubmitted for curation by *'{creator_name}'*.").format(record_title=record_title, creator_name=creator_name) }}

{% if message %} 
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Review the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock md_body %}

invenio_curations/templates/semantic-ui/invenio_notifications/curation-request.review.jinja
{% set curation_request = notification.context.request %}
{% set group = curation_request.receiver %}
{% set creator = curation_request.created_by %}
{% set record = curation_request.topic %}
{% set request_id = curation_request.id %}
{% set executing_user = notification.context.executing_user %}
{% set message = notification.context.message | safe if notification.context.message else '' %}
{% set record_title = record.metadata.title %}
{% set curator_name = executing_user.profile.full_name %}
{% if not curator_name  %} 
    {% set curator_name = executing_user.email %}
{% else %} 
    {% set curator_name = curator_name +  " - " + executing_user.email %} 
{% endif %}

{# TODO: use request.links.self_html when issue issue is resolved: https://github.com/inveniosoftware/invenio-rdm-records/issues/1327 #}
{% set request_link = "{ui}/me/requests/{id}".format(
    ui=config.SITE_UI_URL, id=request_id
    )
%}
{% set account_settings_link = "{ui}/account/settings/notifications".format(
    ui=config.SITE_UI_URL
    )
%}

{%- block subject -%}
       {{ _("👁️ Review started for '{record_title}'").format(record_title=record_title) }}
{%- endblock subject -%}

{%- block html_body -%}
    <table style="font-family:'Lato',Helvetica,Arial,sans-serif;border-spacing:15px">
        <tr>
            <td>{{ _("The metadata curator '{curator_name}' started reviewing the record '{record_title}'").format(curator_name=curator_name, record_title=record_title) }}
            {% if message %}
            {{ _(" with the following message:")}}
            {% endif %}
            </td>
        </tr>
        <tr>
            {% if message %}
            <td><em>{{message}}</em></td>
            {% endif %}
        </tr>
        <tr>
            <td><a href="{{ request_link }}" class="button">{{ _("Check out the curation request")}}</a></td>
        </tr>
        <tr>
            <td><strong>_</strong></td>
        </tr>
        <tr>
            <td style="font-size:smaller">{{ _("This is an auto-generated message. To manage notifications, visit your")}} <a href="{{account_settings_link}}">{{ _("account settings")}}</a>.</td>
        </tr>
    </table>
{%- endblock html_body %}

{%- block plain_body -%}
{{ _("The metadata curator {curator_name} started reviewing the record '{record_title}'").format(curator_name=curator_name, record_title=record_title) }}

{% if message %}
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Check out the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock plain_body %}

{# Markdown for Slack/Mattermost/chat #}
{%- block md_body -%}
{{ _("The metadata curator *{curator_name}* started reviewing the record *{record_title}*").format(curator_name=curator_name, record_title=record_title) }}

{% if message %}
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Check out the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock md_body %}

invenio_curations/templates/semantic-ui/invenio_notifications/curation-request.submit.jinja
{% set curation_request = notification.context.request %}
{% set group = curation_request.receiver %}
{% set creator = curation_request.created_by %}
{% set record = curation_request.topic %}
{% set request_id = curation_request.id %}
{% set creator_name = creator.profile.full_name %}
{% if not creator_name  %} 
    {% set creator_name = creator.email %}
{% else %} 
    {% set creator_name = creator_name +  " - " + creator.email %} 
{% endif %}

{% set record_title = record.metadata.title %}
{% set message = notification.context.message | safe if notification.context.message else '' %}

{# TODO: use request.links.self_html when issue issue is resolved: https://github.com/inveniosoftware/invenio-rdm-records/issues/1327 #}
{% set request_link = "{ui}/me/requests/{id}".format(
    ui=config.SITE_UI_URL, id=request_id
    )
%}
{% set account_settings_link = "{ui}/account/settings/notifications".format(
    ui=config.SITE_UI_URL
    )
%}

{%- block subject -%}
       {{ _("📥 New curation request submitted") }}
{%- endblock subject -%}

{%- block html_body -%}
    <table style="font-family:'Lato',Helvetica,Arial,sans-serif;border-spacing:15px">
        <tr>
            <td>{{ _("The record '{record_title}' was submitted for curation by '{creator_name}'").format(record_title=record_title, creator_name=creator_name) }}
            {% if message %} 
            {{ _(" with the following message:")}}
            {% endif %}
            </td>
        </tr>
        <tr>
            {% if message %} 
            <td><em>{{message}}</em></td>
            {% endif %}
        </tr>
        <tr>
            <td><a href="{{request_link}}" class="button">{{ _("Review the curation request")}}</a></td>
        </tr>
        <tr>
            <td><strong>_</strong></td>
        </tr>
        <tr>
            <td style="font-size:smaller">{{ _("This is an auto-generated message. To manage notifications, visit your")}} <a href="{{account_settings_link}}">{{ _("account settings")}}</a>.</td>
        </tr>
    </table>
{%- endblock html_body %}

{%- block plain_body -%}
    {{ _("The record '{record_title}' was submitted for curation by '{creator_name}'.").format(record_title=record_title, creator_name=creator_name) }}

{% if message %} 
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Review the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock plain_body %}

{# Markdown for Slack/Mattermost/chat #}
{%- block md_body -%}
{{ _("The record *'{record_title}'* was submitted for curation by *'{creator_name}'*.").format(record_title=record_title, creator_name=creator_name) }}

{% if message %} 
{{ _("with the following message:")}}
{{message}}
{% endif %}

[{{ _("Review the curation request") }}]({{ request_link }})

{{ _("This is an auto-generated message. To manage notifications, visit your account settings")}}
{%- endblock md_body %}

invenio_curations/templates/semantic-ui/invenio_requests/rdm-curation/index.html
{# -*- coding: utf-8 -*-

  Copyright (C) 2016-2023 CERN.
  Copyright (C) 2024 Graz University of Technology.

  Invenio-Curations is free software; you can redistribute it and/or modify it
  under the terms of the MIT License; see LICENSE file for more details.
#}

{#
  Renders the rdm-curation request details page.
#}

{% extends "invenio_requests/details/index.html" %}
{% set is_curator = current_user.has_role(config["CURATIONS_MODERATION_ROLE"]) %}
{% set active_dashboard_menu_item = "curation-overview" if is_curator else "requests" %}

{%- block request_header %}

  {% set back_button_url = url_for("invenio_curations.curation_requests_overview" if is_curator else "invenio_app_rdm_users.requests") %}
  {% from "invenio_requests/macros/request_header.html" import inclusion_request_header %}
  {{ inclusion_request_header(
      request=invenio_request,
      record=record,
      accepted=False, 
      back_button_url=back_button_url,
      back_button_text=_("Back to requests")
    ) }}
{%- endblock request_header %}

{% block request_timeline %}
<div
    class="ui container rdm-tab-container fluid rel-pt-2 ml-0-mobile mr-0-mobile"
    id="request-community-submission-tab-container"
  >
    {% if record %}
      <div
        class="ui secondary pointing menu rdm-tab-menu"
        id="request-community-submission-tab"
      >
        <a
          class="active item"
          data-tab="conversation"
          role="tab"
          aria-selected="true"
          aria-controls="conversation-tab-panel"
          id="conversation-tab"
        >
          {{ _("Conversation") }}
        </a>


        <a
          role="tab"
          class="item"
          data-tab="record"
          aria-selected="false"
          aria-controls="record-tab-panel"
          id="record-tab"
        >
          {{ _("Record") }}
        </a>
      </div>
    {% endif %}


    <div
      class="ui bottom attached tab segment active borderless p-0"
      data-tab="conversation"
      role="tabpanel"
      aria-labelledby="conversation-tab"
      id="conversation-tab-panel"
    >
      {{ super() }}
    </div>

    {% if record %}
      <div
        class="ui bottom attached tab segment borderless"
        data-tab="record"
        role="tabpanel"
        aria-labelledby="record-tab"
        id="record-tab-panel"
        hidden="hidden"
      >
        {% set use_theme_basic_template = false %}
        {% set preview_submission_request = true %}
        {% include "invenio_app_rdm/records/detail.html" %}
      </div>
    {% endif %}
  </div>
{% endblock request_timeline %}